### ISSUE TITLE
Is it possible to get GraphQL syntax highlighting for `gql` tags?

### ISSUE THREAD

**Issue by ckruse** [orzechowskid/tsx-mode.el#32]
when working with GraphQL one uses a lot of `gql` tags. Is it possible to highlight them like CSS?

**Comment by orzechowskid** [comment]
basic support should be easy, yes, following a process similar to tsx-mode's CSS-in-JS support.

I say "basic support" because full and proper support would require a tree-sitter grammar.  such grammars exist but are not bundled with the tree-sitter-langs meta-package and so I'm not sure how to check for their presence and use them when available.

let me see what I can do in the short term, and think about what to do in the longer term.

**Comment by orzechowskid** [comment]
ok!  please update your straight.el recipe to use the `chore/modularize` branch of this repo and let me know how it goes.  (I wanted to do some cleanup and refactoring before I added support for gql tagged-template strings, hence the strange branch name).

performance is a little slower than css-in-js probably due to graphql-mode using regexps instead of a tree-sitter grammar.

**Comment by ckruse** [comment]
Thank you very much. After a few hours playing with it: it works as specified, although it is indeed a little bit laggy. Great work! ❤️
